development:
  secret_key_base: '--'
  devise_secret_key: '--'
  aws_access_key_id: '--'
  aws_secret_access_key: '--'

test:
  secret_key_base: '--'
  devise_secret_key: '--'
  aws_access_key_id: '--'
  aws_secret_access_key: '--'

production:
  secret_key_base: '--'
  devise_secret_key: '--'
  aws_access_key_id: '--'
  aws_secret_access_key: '--'

ci:
  secret_key_base: '31c2b3acb116faff57040ae1188b91f1ddb051bc9f05b5aa9bf2b278efa914ccb09a986422fa572940d0a95ec80535ba9e2e02cb0682cc7867c437d41e75132b'
  devise_secret_key: '25d1372ab5fb586daf85e173b3acba11de3c299650db2c474bfb6fffcf16fa466831962309843d9f5b8f943cabbaf897e6ab374efba2eef6983b9a71c4fa78b7'
  aws_access_key_id: '--'
  aws_secret_access_key: '--'